# Generated by Django 2.0.9 on 2019-01-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NetLens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='links',
            table='link',
        ),
    ]
