# Generated by Django 2.0.9 on 2019-02-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NetLens', '0002_auto_20190124_1546'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='links',
            table='links',
        ),
    ]
