# Generated by Django 2.0.9 on 2019-02-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetLens', '0003_auto_20190204_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('movieid', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recommendations',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='links',
            table='link',
        ),
    ]
