# Generated by Django 2.0.9 on 2019-02-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NetLens', '0004_auto_20190204_1603'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='links',
            table='links',
        ),
    ]
