# Generated by Django 2.0.9 on 2019-02-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NetLens', '0005_auto_20190225_1514'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='links',
            table='link',
        ),
    ]
